# Copyright 2026 Yellowbrick Data, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

engine_specific {
  payload_type: "floe.access_methods+proto"
  [floe.ext.floe_access_methods] {
    methods { oid: 403 amname: "btree" }
    methods { oid: 405 amname: "hash" }
  }
}

engine_specific {
  payload_type: "floe.operator_families+proto"
  [floe.ext.floe_operator_families] {
    families { oid: 1976 opfmethod: 403 opfname: "integer_ops" opfnamespace: 11 }
    families { oid: 1977 opfmethod: 405 opfname: "integer_ops" opfnamespace: 11 }
    families { oid: 1994 opfmethod: 403 opfname: "text_ops" opfnamespace: 11 }
    families { oid: 1995 opfmethod: 405 opfname: "text_ops" opfnamespace: 11 }
  }
}

engine_specific {
  payload_type: "floe.operator_classes+proto"
  [floe.ext.floe_operator_classes] {
    # int4 btree opclass
    classes {
      oid: 1978
      opcfamily: 1976
      opcintype: 23
      opcmethod: 403
      opcdefault: true
      opcname: "int4_ops"
      opcnamespace: 11
    }

    # int4 hash opclass
    classes {
      oid: 1979
      opcfamily: 1977
      opcintype: 23
      opcmethod: 405
      opcdefault: true
      opcname: "int4_ops"
      opcnamespace: 11
    }

    # text btree opclass
    classes {
      oid: 3121
      opcfamily: 1994
      opcintype: 25
      opcmethod: 403
      opcdefault: true
      opcname: "text_ops"
      opcnamespace: 11
    }

    # text hash opclass
    classes {
      oid: 3122
      opcfamily: 1995
      opcintype: 25
      opcmethod: 405
      opcdefault: true
      opcname: "text_ops"
      opcnamespace: 11
    }
  }
}

engine_specific {
  payload_type: "floe.operator_access_methods+proto"
  [floe.ext.floe_operator_access_methods] {
    entries { amopfamily: 1976 amopstrategy: 1 amoplefttype: 23 amoprighttype: 23 amopopr: 0 amoppurpose: "s" }  # <
    entries { amopfamily: 1976 amopstrategy: 2 amoplefttype: 23 amoprighttype: 23 amopopr: 0 amoppurpose: "s" }  # <=
    entries { amopfamily: 1976 amopstrategy: 3 amoplefttype: 23 amoprighttype: 23 amopopr: 0 amoppurpose: "s" }  # =
    entries { amopfamily: 1976 amopstrategy: 4 amoplefttype: 23 amoprighttype: 23 amopopr: 0 amoppurpose: "s" }  # >=
    entries { amopfamily: 1976 amopstrategy: 5 amoplefttype: 23 amoprighttype: 23 amopopr: 0 amoppurpose: "s" }  # >
    entries { amopfamily: 1994 amopstrategy: 1 amoplefttype: 25 amoprighttype :25 amopopr :0 amoppurpose: "s" } # <
    entries { amopfamily: 1994 amopstrategy: 2 amoplefttype: 25 amoprighttype: 25 amopopr: 0 amoppurpose: "s" }  # <=
    entries { amopfamily: 1994 amopstrategy: 3 amoplefttype: 25 amoprighttype: 25 amopopr: 0 amoppurpose: "s" }  # =
    entries { amopfamily: 1994 amopstrategy: 4 amoplefttype: 25 amoprighttype: 25 amopopr: 0 amoppurpose: "s" } # >=
    entries { amopfamily :1994 amopstrategy :5 amoplefttype :25 amoprighttype :25 amopopr :0 amoppurpose: "s" } # >
  }
}

engine_specific {
  payload_type: "floe.procedure_access_methods+proto"
  [floe.ext.floe_procedure_access_methods] {
    entries { amprocfamily: 1976 amprocnum: 1 amproclefttype: 23 amprocrighttype: 23 amproc: 0 }
    entries { amprocfamily: 1994 amprocnum: 1 amproclefttype: 25 amprocrighttype: 25 amproc: 0 }
  }
}
