# Copyright 2026 Yellowbrick Data, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ######################
# TODO: PORT PG Catalog
# ######################

functions {
  name { name: "int4_abs" path: "pg_catalog" }
  argument_types { name: "int4" path: "pg_catalog" }
  return_type { name: "int4" path: "pg_catalog" }
  engine_specific {
    payload_type: "floe.function+proto"
    min_version: "9.5"
    [floe.ext.floe_function] {
      oid: 1250
      proname: "int4_abs"
      prolang: 12
      proisstrict: true
      proleakproof: false
      proisagg: false
      proiswindow: false
      provolatile: "i"
      prosrc: "int4_abs"
    }
  }
}

functions {
  name { name: "text_length" path: "pg_catalog" }
  argument_types { name: "text" path: "pg_catalog" }
  return_type { name: "int4" path: "pg_catalog" }
}

functions {
  name { name: "text_upper" path: "pg_catalog" }
  argument_types { name: "text" path: "pg_catalog" }
  return_type { name: "text" path: "pg_catalog" }
  engine_specific {
    payload_type: "floe.function+proto"
    min_version: "9.5"
    [floe.ext.floe_function] {
      oid: 1251
      proname: "text_upper"
      prolang: 12
      proisstrict: true
      proiswindow: false
      proisagg: false
      provolatile: "v"
      prosrc: "text_upper"
    }
  }
}

functions {
  name { name: "int4_add" path: "pg_catalog" }
  argument_types { name: "int4" path: "pg_catalog" }
  argument_types { name: "int4" path: "pg_catalog" }
  return_type { name: "int4" path: "pg_catalog" }
}

functions {
  name { name: "text_concat" path: "pg_catalog" }
  argument_types { name: "text" path: "pg_catalog" }
  argument_types { name: "text" path: "pg_catalog" }
  return_type { name: "text" path: "pg_catalog" }
}

functions {
  name { name: "sum_int4_state" path: "pg_catalog" }
  argument_types { name: "int8" path: "pg_catalog" }
  argument_types { name: "int4" path: "pg_catalog" }
  return_type { name: "int8" path: "pg_catalog" }
  is_aggregate: true
  engine_specific {
    payload_type: "floe.function+proto"
    min_version: "9.5"
    [floe.ext.floe_function] {
      proname: "sum_int4_state"
      prolang: 12
      proisstrict: true
      proisagg: true
      provolatile: "i"
      prosrc: "sum_int4_state"
    }
  }
}

functions {
  name { name: "sum_int4_final" path: "pg_catalog" }
  argument_types { name: "int8" path: "pg_catalog" }
  return_type { name: "int8" path: "pg_catalog" }
  is_aggregate: true
  engine_specific {
    payload_type: "floe.function+proto"
    min_version: "9.5"
    [floe.ext.floe_function] {
      proname: "sum_int4_final"
      prolang: 12
      proisstrict: true
      proisagg: true
      provolatile: "i"
      prosrc: "sum_int4_final"
    }
  }
}

operators {
  name { name: "+" }
  left_type { name: "int4" path: "pg_catalog" }
  right_type { name: "int4" path: "pg_catalog" }
  return_type { name: "int4" path: "pg_catalog" }
  is_commutative: true
  is_associative: true
}

operators {
  name { name: "||" }
  left_type { name: "text" path: "pg_catalog" }
  right_type { name: "text" path: "pg_catalog" }
  return_type { name: "text" path: "pg_catalog" }
  is_commutative: false
  is_associative: false
}

types {
  name { name: "int4" path: "pg_catalog" }
  category: "N"
  engine_specific {
    payload_type: "floe.type+proto"
    [floe.ext.floe_type] {
      oid: 23
      typname: "int4"
      typnamespace: 11
      typlen: 4
      typbyval: true
      typdelim: ","
      typalign: "i"
      typarray: 1007
    }
  }
}

types {
  name { name: "int8" path: "pg_catalog" }
  category: "N"
  engine_specific {
    payload_type: "floe.type+proto"
    [floe.ext.floe_type] {
      oid: 20
      typname: "int8"
      typnamespace: 11
      typlen: 8
      typbyval: true
      typdelim: ","
      typalign: "i"
    }
  }
}

types {
  name { name: "text" path: "pg_catalog" }
  category: "S"
  engine_specific {
    payload_type: "floe.type+proto"
    [floe.ext.floe_type] {
      oid: 25
      typname: "text"
      typnamespace: 11
      typlen: -1
      typbyval: false
      typdelim: ","
      typalign: "i"
    }
  }
}

types {
  name { name: "_int4" path: "pg_catalog" }
  category: "A"
  is_array: true
  element_type { name: "int4" path: "pg_catalog" }
  engine_specific {
    payload_type: "floe.type+proto"
    [floe.ext.floe_type] {
      oid: 1007
      typname: "_int4"
      typnamespace: 11
      typlen: -1
      typbyval: false
      typdelim: ","
      typalign: "i"
      typelem: 23
      typarray: 0
    }
  }
}

casts {
  name { name: "text2int4" path: "pg_catalog" }
  source_type { name: "text" path: "pg_catalog" }
  target_type { name: "int4" path: "pg_catalog" }
  method: "explicit"
}

casts {
  name { name: "int42text" path: "pg_catalog" }
  source_type { name: "int4" path: "pg_catalog" }
  target_type { name: "text" path: "pg_catalog" }
  method: "assignment"
}

casts {
  name { name: "int42_int4" path: "pg_catalog" }
  source_type { name: "int4" path: "pg_catalog" }
  target_type { name: "_int4" path: "pg_catalog" }
  method: "implicit"
}

collations {
  name { name: "default" path: "pg_catalog" }
  locale: "en_US"
}

aggregates {
  name { name: "sum" path: "pg_catalog" }
  argument_types { name: "int4" path: "pg_catalog" }
  state_type { name: "int8" path: "pg_catalog" }
  return_type { name: "int8" path: "pg_catalog" }
  engine_specific {
    payload_type: "floe.aggregate+proto"
    [floe.ext.floe_aggregate] {
      aggfnoid: 0
      aggtransfn: 0
      aggfinalfn: 0
      aggmtransfn: 0
      aggmfinalfn: 0
    }
  }
}
