title: Floecat
description: Floecat notes, architecture, and blog

remote_theme: "mmistakes/minimal-mistakes@4.27.3"

baseurl: "/floecat"
url: "https://eng-floe.github.io"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

atom_feed:
  hide: false

search: true
