package ai.floedb.floecat.metagraph.model;

/**
 * Execution backend for a system object.
 *
 * <p>The enum intentionally mirrors the terminology in {@code FloeCat_Architecture_Book.md}; the
 * concrete RPC/proto definition can replace it once the contract is finalized.
 */
public enum TableBackendKind {
  FLOECAT, // rows generated by Floecat (built-in or plugin)
  ENGINE, // rows generated directly in the engine
  STORAGE // rows written in files in storage
}
