# Copyright 2026 Yellowbrick Data, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

system_namespaces {
  name {
    name: "pg_catalog"
  }
  display_name: "pg_catalog"
  engine_specific {
    [floe.ext.floe_namespace] {
      oid: 11
      nspname: "pg_catalog"
    }
    payload_type: "floe.namespace+proto"
  }
}

system_namespaces {
  name {
    name: "sys"
  }
  display_name: "sys"
  engine_specific {
    [floe.ext.floe_namespace] {
      oid: 3300
      nspname: "sys"
    }
    payload_type: "floe.namespace+proto"
  }
}
